# Generated by Django 2.2 on 2019-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studiomanna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Yogales'), (2, 'Shared dinner'), (3, 'Workshop')], default=1, verbose_name='type'),
            preserve_default=False,
        ),
    ]
